name: Build ESP32 Firmware

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository auschecken
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Python & PlatformIO installieren
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      # 3. Versionsnummer automatisch hochzählen
      - name: Increment Firmware Version
        id: version
        run: |
          VERSION_FILE=include/core/config.h
          CURRENT=$(grep "FirmwareVersion" $VERSION_FILE | sed -E 's/.*"([0-9]+\.[0-9]+\.[0-9]+)".*/\1/')
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT"
          PATCH=$((PATCH+1))
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "Neue Version: $NEW_VERSION"

          # Datei updaten
          sed -i "s/$CURRENT/$NEW_VERSION/" $VERSION_FILE

          # Als Output für weitere Steps
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      # 4. Firmware kompilieren
      - name: Build firmware with PlatformIO
        run: |
          pio run

      # 5. Bin-Datei als Artefakt hochladen
      - name: Upload firmware artifact
        uses: actions/upload-artifact@v3
        with:
          name: firmware-${{ steps.version.outputs.version }}
          path: .pio/build/*/firmware.bin

      # 6. Optional: Commit und push der neuen Version
      - name: Commit updated version
        if: github.ref == 'refs/heads/main'
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add include/core/config.h
          git commit -m "Bump firmware version to ${{ steps.version.outputs.version }}"
          git push