name: Build Firmware

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04

    env:
      PLATFORMIO_CI_SRC: src
      FIRMWARE_NAME: CAN_OBD2_Gateway
      VERSION_FILE: version.txt

    steps:
    # --- Checkout Repository ---
    - name: Checkout
      uses: actions/checkout@v4

    # --- Setup Python ---
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    # --- Install PlatformIO ---
    - name: Install PlatformIO
      run: |
        pip install --upgrade pip
        pip install platformio

    # --- Version Auto-Increment ---
    - name: Auto Increment Version
      id: version
      run: |
        if [ ! -f $VERSION_FILE ]; then
          echo "1.0.0" > $VERSION_FILE
        fi
        old_version=$(cat $VERSION_FILE)
        IFS='.' read -r major minor patch <<< "$old_version"
        patch=$((patch+1))
        new_version="$major.$minor.$patch"
        echo "$new_version" > $VERSION_FILE
        echo "version=$new_version" >> $GITHUB_ENV
        echo "Firmware version: $new_version"

    # --- Build Firmware ---
    - name: Build Firmware
      run: |
        platformio run

    # --- Rename BIN with Version ---
    - name: Prepare Artifact
      run: |
        mkdir -p output
        cp .pio/build/*/*.bin output/${FIRMWARE_NAME}_${{ env.version }}.bin

    # --- Upload Artifact ---
    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: output/